# Base Variables
title: ITESMARENA
subtitle: Estudios Superiores en Medio Ambiente y Recursos Naturales
url: http://itesmarena.edu.do
baseurl: ""

# SASS
sass:
  sass_dir: _sass
  style: compressed

# URLs
permalink: pretty

# Collections
collections:
  careers:
    output: true
    permalink: /instituto/:collection/:name
  teachers:
    output: false

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - node_modules
  - package.json
  - package-lock.json
  - src
  - tailwind.js

menus:
  header:
    - title: Inicio
      url: /
    - title: Instituto
      url: /instituto/
      children:
        - title: Historia
          url: /instituto/historia/
        - title: Ejes Transversales
          url: /instituto/Mision/
        - title: Rector
          url: /instituto/Rector/
    
    - title: Carreras
      url: /instituto/carreras/
    - title: Admisiones
      url: /Admision2025/
    - title: Aula Virtual
      url: https://institutodelambiente.milaulas.com/login/index.php
    - title: Contacto
      url: /contactanos/
    - title: NOTICIAS
      url: /blog/
